Filter expenses larger than 20000 kr on stats
datasektionen/cashflow pull request #104
Opened 2021-10-22 16:14 UTC by elmaxe

Vi ska inte uppmuntra folk till att göra stora utlägg. Det är
en onödig risk och stora utlägg bör tas på faktura eller med
företagskortet. Det är dessutom olagligt att använda sitt
kreditkort för att få flygpoäng.

(Notera att denna implementation filtrerar på summan av varje
utbetalning, och inte varje individuellt utlägg, då det typ
inte gick att implementera.)

Co-authored-by: Herman Karlsson <herkarlsson@gmail.com>
Co-authored-by: Douglas Fischer <anakin_skryter@hotmail.se>

2021-10-22 16:16 UTC, elmaxe commented
Testat lokalt på min dator. Exporterade produktionsdatabasen till min lokala dator och det såg okej ut

2021-10-29 13:36 UTC, oskstr requested changes

2021-10-29 13:36 UTC, oskstr commented on stats/views.py
> +from django.db.models import Q
What's with the unused import? :blush:

2021-10-29 13:36 UTC, oskstr commented on stats/views.py
> +            .exclude(expense__expensepart__amount__gte=30000) \
From my testing, this does not appear to do what you say it does. This excludes all users with an "expense part" that is greater than or equal to `30000`.

What I think you want to do is perhaps change the row above to:
```python
.filter(expense__reimbursement__isnull=False, expense__expensepart__amount__lt=30000)
```
which removes any expense parts that are not less than 30,000.

2021-10-29 13:36 UTC, oskstr commented on templates/stats/index.html
> +        <h4>OBS. Topplistan räknar bara med utbetalningar mindre än 30 000 kr</h4>
In my opinion, I would probably use something other than `<h4>` here which looks quite large:
![Screenshot 2021-10-29 151640](https://user-images.githubusercontent.com/23638900/139442419-73df500a-89bd-46cd-bbbb-0a1f789a5ebf.png)

Maybe opt for `<p>` instead? Looks like this:
![Screenshot 2021-10-29 151708](https://user-images.githubusercontent.com/23638900/139442416-f478c983-f6fb-4af2-a145-32ee28b5d20a.png)

2021-10-29 14:56 UTC, elmaxe commented on stats/views.py
> +            .exclude(expense__expensepart__amount__gte=30000) \
Ahh nice. What we wanted to do but too stupid to realise

2021-10-29 14:58 UTC, oskstr approved these changes
LGTM 👍

2021-10-29 15:16 UTC, merged

2021-11-02 13:07 UTC, niklasvatn commented
@elmaxe röstar annars på att vi tar bort stats