Added "unattest" functionality for firmatecknare
datasektionen/cashflow pull request #134
Opened 2023-04-10 11:42 UTC by TerraDOOM

Added functionality so that people with attest-firmatecknare may unattest expenses, at popular request (Felix Murnion)

2023-04-10 13:00 UTC, DouglasFischer submitted a review, later dismissed
The action should also send a message on the receipt, stating what has been done.

2023-04-10 13:04 UTC, Adasjo commented
Should this really be a feature? The main reason for an "attest" is to approve an expense or something. There should instead be a block that we can't do a payout for the expense and firmatecknare gives a valid reason. As @DouglasFischer mentioned, a message will be sent to the expense owner and the one who did the "attest".

2023-09-19 14:27 UTC, mathiasmagnusson requested changes
I felt like joining in on the request changes train

2023-09-19 14:27 UTC, mathiasmagnusson commented on admin/views.py
> +
This doesn't check that expense hasn't been reimbursed, which could lead to a reimbursed payment being unattested if the expense was loaded before the reimbursement, so the button would still be there.

2023-11-30 19:23 UTC, mathiasmagnusson approved these changes
You should unattest a part of an expense, not the whole expense, but good enough i guess

2023-11-30 20:46 UTC, mathiasmagnusson commented
Vafan vill den inte rebasea för?

2023-12-14 00:47 UTC, merged