Fix receipt check
datasektionen/cashflow pull request #198
Opened 2024-07-31 19:57 UTC by Adasjo

2024-08-01 08:38 UTC, foodelevator commented
omg :exploding_head:

2024-08-01 08:41 UTC, foodelevator reviewed
I approve if I get to join the book burning

2024-08-06 21:24 UTC, Lulcaz approved these changes

2024-08-06 21:30 UTC, Lulcaz commented on templates/admin/confirm/overview.html
> +{% block title %}kontrollera kvitton{% endblock %}
Should have upper case k:

{% block title %}Kontrollera kvitton{% endblock %}

2024-08-06 21:38 UTC, Lulcaz commented on templates/admin/main.html
> +                            Bekräfta i kvitto
Should be something along the lines of "Kontrollera kvitton"

2024-08-12 13:53 UTC, DouglasFischer requested changes
Underkända formuleringar
GOGR

2024-08-13 22:54 UTC, DouglasFischer requested changes
Lägg till att det är kvittots giltighet som kontrolleras.

För nuvarande oklar formulering.

GOGR

2024-08-14 13:49 UTC, DouglasFischer requested changes
FTFY

2024-08-14 13:49 UTC, DouglasFischer commented on admin/views.py
> +            return HttpResponseForbidden("Du har inte rättigheterna för att bekräfta kvitton")
return HttpResponseForbidden("Du har inte rättigheterna för att bekräfta kvittons giltighet")

2024-08-14 13:49 UTC, DouglasFischer commented on admin/views.py
> +            content='Jag har bekräfta kvittots giltighet.'
content='Jag har bekräftat kvittots giltighet.'

2024-08-14 13:49 UTC, DouglasFischer commented on admin/views.py
> +            return HttpResponseForbidden("Du har inte rättigheterna för att avbekräfta kvitton")
return HttpResponseForbidden("Du har inte rättigheterna för att ta bort bekräftelse av kvittons giltighet")

2024-08-14 13:49 UTC, DouglasFischer commented on templates/admin/confirm/overview.html
>      <label for="digital" style="padding-right: 0.5em;">Visa endast digitala</label><input v-model="digital" type="checkbox" id="digital" /><br />
<p>Här kan du hitta alla kvitton vars giltighet inte bekräftats.</p>

2024-08-14 13:49 UTC, DouglasFischer commented on templates/index.html
> +        <li><b>Kvittokontroll.</b> Sektionens kassör bekräftar att kvittot uppfyller kravet för ett kvitto samt ser att det inscannade kvitto är av god kvalitet</li>
<li><b>Kvittokontroll.</b> Sektionens kassör bekräftar att kvittot uppfyller kraven för ett giltigt kvitto samt ser att det inskannade kvitto är av god kvalitet</li>

2024-08-14 13:49 UTC, DouglasFischer commented on templates/expenses/show.html
> +                    btn_message: "Godkänd bekräftelse",
btn_message: "Godkänn bekräftelse",

2024-08-14 13:49 UTC, DouglasFischer commented on templates/expenses/show.html
> +                        this.expense.btn_message = "Godkänd bekräftelse"
this.expense.btn_message = "Godkänn bekräftelse"

2024-08-14 13:49 UTC, DouglasFischer commented on templates/expenses/show.html
> +                <th>Bekräftat:</th>
<th>Giltighet Bekräftad:</th>

2024-08-14 13:49 UTC, DouglasFischer commented on templates/expenses/confirmation.html
>          {% if expense.is_digital %}
Egentligen behövs det inte längre skiljas på digitala och analoga kvitton med det får ni fixa senare IG.
Eller kanske nice för miljöstatistiken

2024-08-14 13:58 UTC, DouglasFischer approved these changes

2024-08-14 13:58 UTC, merged