Fixes the edit function
datasektionen/cashflow pull request #65
Opened 2018-09-12 10:00 UTC by Guaschman

This PR hopefully fixes the edit function for expenses as well as enforces a non-negative sum limit on new expenses. Would appreciate feedback from @bullfest and/or @jonasdahl.

2018-09-13 14:01 UTC, bullfest requested changes

2018-09-13 14:01 UTC, bullfest commented on expenses/views.py
> +    #raise Http404("Under underhåll")
Just remove it instead.

2018-09-13 14:01 UTC, bullfest commented on expenses/views.py
> +        if len(list(filter(lambda x: int(x) < 1, request.POST.getlist('amount[]')))) > 0:
Replace with something like:
```any(map(lambda x: x <= 0, request.post.getlist('amount[]')))```

Not sure about the best way for getting the data, but this is shorter and syntactically more similar to what we want to do.

2018-09-13 14:01 UTC, bullfest commented on invoices/views.py
> +        return HttpResponseRedirect(reverse('expenses-new'))
Same as earlier comment

2018-09-13 14:01 UTC, bullfest commented on expenses/views.py
> +            continue
Maybe not fail silently here.

2018-09-13 14:06 UTC, jonasdahl commented
Småsaker, helt klar mergebart. Nice att nån tog tag i det!

2018-09-13 14:32 UTC, bullfest commented
Ett kvitto bör nog inte heller vara redigerbart om det har attesterats @Guaschman

2018-09-13 14:39 UTC, jonasdahl commented
Jo det tycker jag, men då ska det bli oattesterat igen

2018-09-13 15:02 UTC, Guaschman commented
Det är precis så det fungerar i den här PR, om man ändrar på kvittot så kommer alla kvittodelar behöva attesteras igen.

2018-09-13 15:13 UTC, jonasdahl commented
Ja, det låter som väldigt rimligt!

2018-09-14 18:29 UTC, bullfest commented
Ahhh, tänkte inte på att man kan lösa det så. I ursprungliga versionen så låste en attestering att man kan redigera, känns som en bra lösning :)

2018-09-14 18:29 UTC, bullfest approved these changes

2018-09-15 11:12 UTC, merged

2018-09-17 13:28 UTC, bullfest commented
Nu är det deployat :smile: